version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/contrib/prometheus"
      - "/contrib/otel"
      - "/contrib/fiber"
      - "/examples"
      - "/integration"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
